apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kubernetes.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: search-service-tcp
  name: search-service-tcp
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3010
  selector:
    io.kompose.service: search-service
  type: LoadBalancer
